spring:
  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/Db_Booking
    password: 123456789
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5050
